services:
  web:
    image: ticketing.azurecr.io/samples/bunmongo:1.0.0
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    command: ["bun", "start"]
    depends_on:
      - mongo
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
  mongo-express:
    image: "mongo-express"
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
    depends_on:
      - mongo
